on:
  workflow_call:
    inputs:
      PROJECT:
        required: true
        type: string
      SCOPE:
        required: true
        type: string
      BUILD_VERSION:
        required: true
        type: string
      BUILD_BRANCH:
        required: true
        type: string

jobs:
  build-image:
    name: Build Docker Image
    continue-on-error: false
    runs-on: ubuntu-latest
    env:
      ACCOUNT: 273019133067
    steps:
      - name: Debug
        run: |
          cd $GITHUB_WORKSPACE && pwd && ls -las
          cd $GITHUB_WORKSPACE/deploy && pwd && ls -las
          cd $GITHUB_WORKSPACE/.. && pwd && ls -las
      - name: Checkout Build repository
        uses: actions/checkout@v3
        with:
          repository: Pinoga/tradingbuild
          ref: ${{ inputs.BUILD_BRANCH }}
          path: deploy
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::273019133067:role/github-oidc-role
          aws-region: us-east-1
      - uses: actions/cache@v3
        with:
          path: .
          key: ${{ github.sha }}
      - name: Debug
        run: |
          cd $GITHUB_WORKSPACE && pwd && ls -las
          cd $GITHUB_WORKSPACE/deploy && pwd && ls -las
          cd $GITHUB_WORKSPACE/.. && pwd && ls -las
      - name: Build Docker Image
        run: |
          chmod +x deploy/build-image.sh
          ./deploy/build-image.sh us-east-1 $ACCOUNT ${{ inputs.SCOPE }} ${{ inputs.PROJECT }} $GITHUB_SHA ${{ inputs.BUILD_VERSION }}